### ISSUE TITLE
Adding the ETag value in the response body

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1027]
We have seen that using the ETag header can cause a number of problems with CDN and cache handling.

A proposition would be to add its value as part as the response:

```
{
  "data": [...],
  "last_modified": "1480331301530"
}

**Comment by Natim** [comment]
Alternatively we could use a meta namespace:

```
{
  "data": [...],
  "meta": {
    "last_modified": "1480331301530"
  }
}
```

**Comment by Natim** [comment]
We could probably do the same thing with all the other meta information:

```
{
    "meta": {
      "total_records": 357,
      "next_page": "https://firefox.settings.services.mozilla.com/v1/buckets/blocklists/collections/certificates/records?_limit=3&_token=eyJvZmZzZXQiOjMsImxhc3RfcmVjb3JkIjp7Imxhc3RfbW9kaWZpZWQiOjE0ODQ3MDQ1ODA4OTR9fQ%3D%3D",
      "last_modified": 1484704581273,
      "date": "1484838228331"
    }
}
```

**Comment by leplatrem** [comment]
Agree. 

This is what JSONApi recommands too: http://jsonapi.org/format/#document-meta

Maybe, the `next_page` could go to `"links": {"next": "https://"}` so that we stick to their spec too: http://jsonapi.org/format/#document-links

**Comment by glasserc** [comment]
For those of you following along at home, one specific problem we've seen is that the CDN will gzip a response and then strip the ETag. Since we're using ETags for concurrency control, this breaks syncing and everything else.

There's an argument that we're using ETag wrong, since the RFC says an ETag corresponds to a *representation* rather than the resource itself. That would make the CDN behavior correct, since gzip'ing a response means producing a new representation. There's also the `Last-Modified` / `If-Unmodified-Since` headers. We could also perform a test with "weak" ETags, which only change if the resource is no longer the same "semantically". Maybe the CDN would preserve a "weak" ETag, even if it gzips the response. On the other hand, this might break all our existing clients, which assume ETags are just string-encoded integers :(

@Natim proposed in #1102 getting rid of ETags completely. I'm not crazy about the idea of removing ETag, since it will break our old clients. I'd be in favor of adding new concurrency-control information, whether that's within a `meta` tag or as `Last-Modified` or something else.

**Comment by leplatrem** [comment]
Just for the reference: we used to rely on `If-Modified-Since` but got rid of them because they are not opaque, in the sense that they should contain an HTTP date, with a precision *to second*.

**Comment by leplatrem** [comment]
Does not seem useful anymore
