### ISSUE TITLE
Make serve recipe is failing

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto#1092]
Seems related to #1087
```
gsurita-30820:kinto gsurita$ make serve 
.venv/bin/kinto --ini config/kinto.ini init
Select the backend you would like to use: (1 - postgresql, 2 - redis, default - memory) 
INFO   Created config /Users/gsurita/kinto/config/kinto.ini
.venv/bin/kinto --ini config/kinto.ini migrate
/Users/gsurita/kinto/kinto/core/initialization.py:567: UserWarning: HTTPS is not enabled
  warnings.warn('HTTPS is not enabled')
INFO   Running kinto 6.0.0.dev0. 
echo '{"name":"kinto","version":"5.3.1-118-g5fc2dedf","source":"https://github.com/gabisurita/kinto/","commit":"5fc2dedfc0a75d9f337ccdbcc935fa051f377164"}' > version.json
.venv/bin/kinto --ini config/kinto.ini start --reload
usage: kinto [-h] [-n NAME] [-s SERVER_TYPE] [--server-name SECTION_NAME]
             [--reload] [--reload-interval RELOAD_INTERVAL] [-b] [-v] [-q]
             [config_uri] [config_vars [config_vars ...]]
kinto: error: unrecognized arguments: http_port=8888
make: *** [serve] Error 2
```

**Comment by gabisurita** [comment]
https://github.com/Pylons/pyramid/blob/master/HISTORY.txt#L45

**Comment by glasserc** [comment]
It seems like `pserve` had a [massive rewrite upstream](https://github.com/Pylons/pyramid/pull/2805) which breaks us in a couple of ways.

- It seems like moving from optparse to argparse (https://github.com/Pylons/pyramid/pull/2864/) changed the semantics of an argument string like `['pserve', 'config.ini', '--reload', 'http_port=8080']`. For some reason, the argument parser fails to parse this, but it will parse correctly if `--reload` comes either before the INI file or after the variable.

- It seems like the implementation of `pserve` used to re-invoke the same command as `sys.argv`, but now specifically recursively invokes `pserve` from inside a "monitored" reloader process. The second (inner) execution then tries to parse `kinto serve` arguments with `pserve` and totally fails.

It seems like we'll have to rewrite our `kinto serve` code to make it work with Pyramid 1.8. Since master is kind of broken right now, I think we should revert the change until someone has time to do that. In the meantime, @gabisurita points out that if you remove `--reload` from the `Makefile`, then everything works OK (but without reloading). We could make that change instead and create an issue to track it.

**Comment by Natim** [comment]
After investigation, it seems that `--reload` call `hupper` which takes sys.argv instead of the previous argv.

**Comment by Natim** [comment]
I made a pull-request upstream that should handle the matter: https://github.com/Pylons/pyramid/pull/2962/files
