### ISSUE TITLE
ETag is only returned on GET

### ISSUE THREAD

**Issue by magopian** [Kinto/kinto#110]
Shouldn't it also be returned on other verbs, like POST/PATCH/PUT...?

**Comment by leplatrem** [comment]
I also think so.

Since the protocol implementation is done in Cliquet, let's track this there https://github.com/mozilla-services/cliquet/issues/352

I leave the issue opened here, we'll close it when fixed upstream :)

**Comment by ametaireau** [comment]
First-hand, it seems weird to have these `Etags` returned on something else than `GET`s, because it can be understood that it applies to the resource that was queried. For intance, if you do a `POST` on `/records` and that an `Etag` is returned. Is it supposed to be matched against `/records` or `/records/{id}`.

At least, we should be sure to document this and make sure it doesn't prevent the clients from working like they should.

**Comment by leplatrem** [comment]
Done, available in 1.4.0
