### ISSUE TITLE
Should scripts still obey "readonly"?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1236]
If scripts are intended to be our "escape hatch" to provide commands to administrators that shouldn't be run by users. For this reason, they may need to be run in "maintenance mode", where users' access to them is tightly constrained. For example, you may want to disable write access to users when rebuilding quotas. However, every script that makes this sort of change right now checks for whether `readonly` is set, and if it is, refuses to operate. Should they?

Argument in favor: If an administrator sets "readonly", they may expect all Kinto-related things that read the config file to be readonly. Violating that expectation may be an unpleasant surprise.

Argument against: If an administrator wants to switch user access to readonly while they do maintenance, there's no obvious way to do that. The only obvious/clean way I can think of is to run Kinto with a config file that's readonly, and then copy the file and edit it to make it not readonly for scripts.

Thoughts?

**Comment by Natim** [comment]
Initially, the reason we have a readonly mode is to tell Kinto that the database user configured has only read-only access to the database.

My understanding is that readonly should not be used as a maintenance mode feature.
The maintenance mode is currently set at the nginx level where access to the Python worker is cut for the duration of the maintenance.

Maybe you want to add a maintenance mode feature to Kinto, but I don't think we should use readonly for that. However if it is your intention, you can remove the if in your command; the if in the delete-collection one was because in the kinto-settings setup we have both instances with read-only access to the database and instances with write access to the database.

**Comment by glasserc** [comment]
Fantastic, thank you.
