### ISSUE TITLE
Accounts: Unable to create a user using POST with an admin authentication

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1281]
```'message': 'data.id in body: Username and account ID do not match.'```

**Comment by leplatrem** [comment]
Can you send config and request please?

This is explictly tested so I'm surprised...

**Comment by Natim** [comment]
```ini
#
# Auth configuration.
#
kinto.userid_hmac_secret = fcc3...d6b2dfd3f9970b

# Put your user id there instead to only allow the admin to create buckets.
kinto.bucket_create_principals = account:foo

multiauth.policies = account
multiauth.policy.account.use = kinto.plugins.accounts.authentication.AccountsAuthenticationPolicy
kinto.account_create_principals = account:foo
kinto.account_write_principals = account:foo


kinto.includes = kinto.plugins.default_bucket
                 kinto.plugins.admin
                 kinto.plugins.accounts
                 kinto.plugins.history
                 kinto_attachment
```

```echo '{"data": {"idi": "new_user", "password": "azerty"}}' | http POST http://localhost:8888/v1/accounts --auth foo:bar```

**Comment by glasserc** [comment]
The tests use `account_write_principals` and `account_read_principals`, but don't have `account_create_principals` (which is the setting mentioned in the documentation). Adding `account_create_principals` breaks everything. (I'll open a PR soon.) Probably we should rerun the tests with a few different valid combinations of settings (create, read+write, create+read+write...).

**Comment by glasserc** [comment]
OK, so setting `account_create_principals` gets you into an interesting bootstrapping problem where you can't create an account without being an admin, but you can't be an admin without creating the account. So that's why all the tests failed. However, what actually happened for me when I reproduced Rémy's problem is that the tests don't consider you an admin unless you also have account_write permission. This makes some sense -- probably anyone should be able to create their own account, so having that permission doesn't make you an admin -- but it's definitely missing from the documentation.
