### ISSUE TITLE
Add a kinto init command

### ISSUE THREAD

**Issue by almet** [Kinto/kinto#129]
We should have a kinto command which allow to:
- Bootstrap a configuration file, with `kinto init`;
- Run the migrations with `kinto migrate`;
- Run the server with `kinto start`.

This is related to https://github.com/mozilla-services/cliquet/issues/327, which aims to provide a `start` command for cliquet, but we shouldn't ask our clients to type "cliquet": that should be completely opaque to them.

**Comment by ametaireau** [comment]
In order to accomplish this, a new command should be registered.

[See how](https://github.com/mozilla-services/cliquet/blob/master/setup.py#L55-L59) entry points are being handled in the Cliquet project.

You should be able to do this by registering an entry point for the name "kinto". Then, you should use [argparse](https://docs.python.org/2.7/library/argparse.html) with [subparsers](https://docs.python.org/2.7/library/argparse.html#sub-commands) in order to handle the different commands.

**Comment by oak11** [comment]
I came across a library click (http://click.pocoo.org/5/)? I guess it would be helpful for other commands also.

**Comment by leplatrem** [comment]
Good idea @oak11!

I think we have to distinguish the `kinto init` from the two others. Indeed, for `init` the user will be prompted for values and options. Whereas for `migrate` (and `serve`), it will only consist in cabling the existing `pserve` and `cliquet migrate` existing commands.

The hardest part of the `init` command is to implement the prompts with a nice presentation. That's why we can try to find some existing tools that could simplify the task. `pcreate` and `cookiecutter` could be some good candidates :)

From what I read, `click` is a helper to implement a command with options like `--count=5`. There are many tools that provide this functionnality (see below), including some from the standard python library. As a rule of thumb, when this happens, we shall never choose without list our needs. And so far, in terms of command-line options, I haven't thought of anything special!

----------

Tools for CLI parsing:

- http://docopt.org
- http://pypi.python.org/pypi/clize
- http://pypi.python.org/pypi/begins

Toolkits:

- http://builtoncement.com
- https://plumbum.readthedocs.org/en/latest/

**Comment by oak11** [comment]
Thats true, I'll go through those links. For now, I'll continue working on the init command.  Thanks for the tools and toolkits listed above, they seem interesting to use. I'll try working with them once the init command is done.

**Comment by leplatrem** [comment]
Done in 1.9.0
