### ISSUE TITLE
Quotas: KeyError collection_count

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1307]
https://sentry.prod.mozaws.net/operations/kinto-webextensions-prod/issues/634625/

```
KeyError: 'collection_count'
(3 additional frame(s) were not displayed)
...
  File "/usr/local/lib/python3.5/site-packages/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/usr/local/lib/python3.5/site-packages/zope/interface/adapter.py", line 607, in subscribers
    subscription(*objects)
  File "pyramid/config/adapters.py", line 130, in subscriber_wrapper
    return derived_subscriber(*arg)
  File "statsd/client.py", line 30, in _wrapped
    return_value = f(*args, **kwargs)
  File "kinto/plugins/quotas/listener.py", line 144, in on_resource_changed
    bucket_info['collection_count'] += 1
```

**Comment by glasserc** [comment]
I believe this is the aftermath of https://github.com/Kinto/kinto/pull/1271. After some investigation with @jasonthomas, we believe that the script didn't actually run over all of the affected users -- in particular, there appear to be 14 that weren't covered by the second run of the rebuild-quotas script. We think this is due to #1267 not having landed yet. Rerunning rebuild-quotas should fix it (and any other users whose quotas weren't actually rebuilt). Since it's been a month and a half and today is the first occurrence of this, it seems like there's no real urgency, so we're going to wait until Monday to rerun it.

**Comment by glasserc** [comment]
This should be fixed now that we reran the script.
