### ISSUE TITLE
Add Memcached to dockerfile and docker compose setup.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1335]
Following the addition of Memcached as a cache backend.

**Comment by emamurho** [comment]
Hi Natim, 

I'm new to kinto project and require clarification on this issue.

Do you mean to add some pip install command to [dockerfile](https://github.com/Kinto/kinto/blob/master/Dockerfile) and update docker compose[ yml file](https://github.com/Kinto/kinto/blob/master/docker-compose.yml)? Are there any other relevant files work on?

**Comment by leplatrem** [comment]
Thanks for your interest!

Actually, adding `memcache` as an extra dependency here: https://github.com/Kinto/kinto/blob/master/Dockerfile#L21

And add the necessary changes in the yml file to add a link to a memcache container and add the configuration values so that it would be the configured cache backend

**Comment by mayurvadhavana** [comment]
Hello, I am intermediate user of python, and would like to contribute myself on this project. Can I work on it? This is my first project. Thanks

**Comment by leplatrem** [comment]
Hi @mayurvadhavana !
Thanks for your interest in the project!
I don't know if @emamurho is still working on this :) 
Please note also that this precise issue is more about Docker than Python. 
You could look into #1334 otherwise :)
Enjoy!

**Comment by emamurho** [comment]
Hi @leplatrem thanks for asking am still on it :) sorry @mayurvadhavana  :)
