### ISSUE TITLE
Get rid of `make build-requirements`

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#1512]
During a conversation with @peterbe, we realized there were several ways of managing requirements.

Obviously, we agreed on the main necessity: reproducibility and environments consistency. We want to control the dependencies versions going to production.

Currently, in Kinto we have:
* the top-level dependencies (with optional range) in `setup.py`
* the whole dependencies list and their versions in `requirements.txt`
* we deploy kinto using the constraints of `requirements.txt` to keep deps under control
* pyup that opens a PR when a new dependency is available (which runs the tests)

So far, so good.

What was discussed is the fact that:

* The requirements.txt constraints are not used to run the tests on TravisCI
* The requirements.txt constraints are not used to initialize the developer local virtualenv
* We don't edit requirements.txt constraints manually. We run `make build-requirements` during the release process (which basically runs `pip install + freeze` to take the latest versions in range of `setup.py`) and rely on unit-tests (NB. we have 100% coverage)

This leads to situations where:

* Newcomers will fail at installing their dev environment because of an undesired upgrade
* Undesired upgrades can block unrelated contributions.
  * Example:
  * A contributor pushes some documentation changes, no change to the code base
  * CI fails because a backward incompatible upgrade was released and makes the code fail
  * We open a PR to fix the compatible version range in `setup.py`, and merge.
  * We can then merge/rebase the documentation PR
* Some dependency upgrade was not never ran locally by any developer. The dependency upgrade was just tested in unit/integration tests, and deployed.

Alternatively we could:
* Use the requirements constraints in dev + CI
* Remove the  `make build-requirements` part and let individual developers (or pyup) upgrade dependencies by editing `requirements.txt` manually (or using something like `hashin`)

Thoughts?

**Comment by glasserc** [comment]
I'm a bit surprised to hear that `The requirements.txt constraints are not used to initialize the developer local virtualenv`. `dev-requirements.txt` *is* used by the `make install-dev` command, but I see that (like you say) the `requirements.txt` file is essentially completely ignored. Similarly, travis runs `make install-dev` and `tox`, and `tox` depends on `dev-requirements.txt`, but not `requirements.txt`. Are we even sure that we deploy kinto with the requirements in the `requirements.txt`? I'm not sure we do. Compare with e.g. https://github.com/mozilla-services/kinto-dist/blob/master/Dockerfile#L25, which explicitly depends on a set of dependencies set outside this project. I suspect that the requirements.txt file serves no purpose whatsoever.

1. What purpose should `requirements.txt` serve? My instinct is to make the `requirements.txt` actually obligatory by putting it in the Makefile, setup.py or whatever. But honestly I'm not an expert at Python packaging in general so I'm willing to go along with whatever the usual thing in this ecosystem is.
2. How should `requirements.txt` be updated? Personally, I prefer using something like pyup to upgrade one dependency at a time rather than bump a whole bunch of them using `make build-requirements` just before a release. But I don't have a strong opinion on the subject.

**Comment by leplatrem** [comment]
1. We should use the requirements.txt everwhere (local dev, travis, Dockerfile)
And probably switch to some recent stuff like Pipfile (+Pipfile.lock)
2. We get rid of that build-requrirements command and let pyup be the main source of updates. A developer can still contribute a PR that upgrades to a particular release out of the current range (tech debt, new required feature, etc.)

Actually, bulk upgrading requirements during the release PR is not the main issue here, since we have a very good code coverage (but we need 1. !!)

**Comment by Natim** [comment]
If you always rely on the requirements.txt file with constrained version then you never updates your dependencies unless your setup pyup or a process to upgrade your dependencies.

Previously we assumed that upgrading a dependency was a wish-able thing that we wanted to do as soon as possible. If it breaks we will detect it at last before doing the release because we run our release pull-request on the CI while tagging the list of dependencies.

It is fine to use pyup even if having pull-request every few hour is a bit annoying.

In anycase you should never use setup.py to constraint dependencies for a library because you can endup in a project where a lib relies on a version and another lib on another version. (It happens a lot especially requests for instance)

To prevent breaking developers environments we took some precautions:

- We have cronjob that run the CI on master periodically to tell us if a dependency failed.
- We have ci on each pull-request so each time we merge we know that the dependency set is right,
- If it break for someone contributing, they can file an issue and we handle it.
- Each release comes with a `requirements.txt` file that can be use to constraint pip dependencies versions and make sure to have reproducible installation (that we use with kinto-dist when releasing)

In Kinto we now have pyup so the `requirements.txt` file is always kept up-to-date.

I know people that use it to install the dependencies and in that case they use the last validated version.

**Comment by leplatrem** [comment]
Thanks for your feedback! 

I think we should still consider that these points are problematic:
- undesired upgrades in pull-requests (see my comment above)
- contributors might not run the same set of versions 
- local dev and CI might not run the same set of versions

> If you always rely on the requirements.txt file with constrained version then you never updates your dependencies unless your setup pyup or a process to upgrade your dependencies.

Yes, that would be the plan. Since we already have pyup by the way.

It wouldn't be very different than today. Except that we would not run this `make build-requirements` right before releasing, that introduces changes at the last moment. 

> In anycase you should never use setup.py to constraint dependencies for a library 

Agree, not planned to do that.

> (that we use with kinto-dist when releasing)

No entirely true actually, we don't use the `requirements.txt` from the Kinto repo to build the one from kinto-dist
https://github.com/mozilla-services/kinto-dist/blob/ea1ac50c2c1b9c983c81843f1a421c964b63db3e/Makefile#L37-L38
So technically, our only seatbelt in kinto-dist before launching to prod is the end-to-end/functional test there.

We never had problems of that sort so far, but we can still do better than the current situation.

**Comment by peterbe** [comment]
For the record, when setting up pyup you have choices. If you split up your dependencies as `requirements/default.txt` and `requirements/constraints.txt` you can tell PyUp to only bother checking `requirements/default.txt` and (I've never done this but I assume it's possible) only security alerts on `requirements/constraints.txt`. Then you don't get flooded with pyup pull requests for "trivial" packages like `requests`, `six` or `botocore`. 

I failed to do this with [Tecken](https://github.com/mozilla-services/tecken/blob/master/requirements.txt) so now I get [PRs](https://github.com/mozilla-services/tecken/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) for all sorts of "unimportant" packages.
