### ISSUE TITLE
Deleting a collection doesn't delete access_control_entries for its children

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1647]
`buckets.py` has an event listener that ensures that when a bucket is deleted, everything underneath it is recursively deleted. `collections.py` has one too but it doesn't appear to be as robust -- it doesn't have a wildcard to match objects more than one level below it (which might be OK, since only records are below collections now), and `delete_object_permissions` is only called on the collection rather than its children.

**Comment by janani-sridhar** [comment]
I'd like to work on this issue.

**Comment by OhadArzouan** [comment]
Is this still relevant? @janani-sridhar are you on this? If not I'd like to take a look.

**Comment by alexryabkov** [comment]
@janani-sridhar @OhadArzouan Are you guys on this one? I can pick it up if needed.

**Comment by Natim** [comment]
@alexryabkov if you can figure it out, please do.

**Comment by janani-sridhar** [comment]
@OhadArzouan sorry for the lack of response. sorry I wasn't able to work on it.

**Comment by leplatrem** [comment]
Unfortunately, as awkward as it would look, it is not :( (because of #710)

The notion of *collection* in Kinto core is different, and so is the related test in `kinto/tests/core/resource/test_object_permissions.py`. I'm sorry, I know this is confusing.

Instead you should add a new test in `CollectionDeletionTest` in `tests/test_views_collections.py`

You can run this individual test with `py.test -k test_permissions_are_removed...`

Have fun ;)

**Comment by alexryabkov** [comment]
@leplatrem Thanks, will do my best ))

**Comment by alexryabkov** [comment]
@Natim @leplatrem Guys, please take a look at my PR when you have time. Please let me know if something is wrong, I'm a newbie)))
