### ISSUE TITLE
Kinto onboarding experience (part 2)

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#1734]
These is a followup from #1733 with random feedback with onboarding when trying to use the [accounts plugin](http://docs.kinto-storage.org/en/stable/api/1.x/accounts.html).

Started with updating my `config/kinto.ini` with:

```
kinto.includes = kinto.plugins.default_bucket
                 kinto.plugins.admin
                 kinto.plugins.accounts
```

Restarting the server goes smoothly. The admin loads fine and renders a new entry for *Kinto Account Auth*. I never created any Account just yet, though out of curiosity I try to log in using silly:silly:

![](https://i.imgur.com/0OTeatP.png)

Tadaa:

![](https://i.imgur.com/7UMpDFv.png)

Wait, what?

Oh. It seems it actually used the Basic Auth strategy instead of the account one for login. This is odd and confusing as fsck.

Actually, I didn't went further with toying around with the admin as it looks broken to me. This is a little sad.

**Comment by leplatrem** [comment]
You are right this is not supposed to happen! 

So, basically the issue here is:
* the `account` capability is exposed since the plugin was enabled
* the configured policies don't mention `account` in the `multiauth.policies` 
* the Kinto Admin thinks the server can authenticate users with account, where it can't.

I think the solution to this is would be to raise a configuration error if the account plugin is included but the policy is not enabled in `multiauth.policies` setting as described in the docs docs.kinto-storage.org/en/stable/api/1.x/accounts.html
