### ISSUE TITLE
What should `event.payload["timestamp"]` represent?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto#1769]
Refs #945 and #1731. The documentation describes the timestamp field as representing "the time of the event". However, as far as I can tell, the `timestamp` field in an event represents a collection timestamp calculated relatively early in the request, before the action that triggered event happened. It doesn't represent the time that the event happens, nor the current last_modified / collection_timestamp of anything reflected in the event.

I think I'd like to change the `timestamp` key in the payload to correspond to the updated collection timestamp of the `(parent_id, collection_id)` for which the event was fired.

**Comment by leplatrem** [comment]
I would agree with changing that indeed: use the current timestamp before serving the response instead of the one when the request kicks in.

We should still be able to have individual or intermediate timestamps in the `impact_records` attribute I believe.

More generally, we should tackle #945, the semantics of the «global» fields of an event are wrong. 

> Note: if someone reads this, the terms *collection* and *records* in this issue represents the internal notion of `kinto.core`, and applies to buckets, groups, collections, records, accounts... in kinto. See #710

**Comment by glasserc** [comment]
Thinking about this further, I think that although #1770 is a valid short-term fix, it feels a little odd for me to bless one specific attribute about the resource as "part of the payload". Maybe the right fix is for the payload to include the `model` or `resource` or something so that the recipient of the event can decide what attributes it wants.
