### ISSUE TITLE
Setting kinto.http_host disturbs redirections

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#218]
Scenario at PyconFr: 

- user A runs kinto on `0.0.0.0:8888` with make serve
- user B tries accesses on user A instance through local Wifi `192.168.1.12:8888`
- user B is redirected to `http://localhost:8888/v1`

Indeed, in default configuration `kinto.http_host` is equal to `localhost:8888`. And we use this setting to force `request.host` if it is defined.

We had done that in cliquet a while ago, because otherwise the pagination  `Next-Page` URL would not contain the port.

I realize this is not acceptable :) Especially because the same information is duplicated several times:

* `[server:main] host = 0.0.0.0 port = 8888`
* `kinto.http_host = 0.0.0.0:8888`
* `[uwsgi] http-socket = 127.0.0.1:8888`

**Comment by Natim** [comment]
Note that this settings don't have anything to do we each other.

The fact that they have the same values in development is a pure chance.

```
host = 0.0.0.0
port = 8888
```

Is use to serve the app with waitress (which is used in production only)

```
[uwsgi]
socket = 127.0.0.1:8888
```

We will never have to use such a setup because in production we will use file sockets.

```
socket = /run/wsgi/kinto.sock
```

```
kinto.http_host = localhost:8888
```

This one is the public address when kinto have to name itself.

So in production the setup will be:

```
[uwsgi]
socket = /run/wsgi/kinto.sock

kinto.http_host = kinto.services.mozilla.com
```

As you can see we need to keep all of this settings.

``kinto.http_host`` should never ever looks like ``0.0.0.0:8000`` because 0.0.0.0 is not a correct ip address to name a kinto server.
