### ISSUE TITLE
Safety checks on startup for backends configurations

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#228]
Currently if a storage or cache backend is set for the permission backend setting, an obscure error happens internally.

```
exception" : "Traceback (most recent call last):\n  File \"/data/kinto/lib/python2.7/site-packages/pyramid/tweens.py\", line 21, in excview_tween\n    response = handler(request)\n  File \"/data/kinto/lib/python2.7/site-packages/pyramid/router.py\", line 118, in handle_request\n    root = root_factory(request)\n  File \"/data/kinto/lib/python2.7/site-packages/cliquet/authorization.py\", line 91, in __init__\n    self._check_permission = request.registry.permission.check_permission\nAttributeError: 'PostgreSQL' object has no attribute 'check_permission'",
```

At startup, we could check that each backend configured is a proper subclass of the appropriate interface.

```python
if not isinstance(config.registry.storage, cliquet.storage.BaseStorage):
    raise ConfigurationError('Time to get sober :)')
```

**Comment by tarekziade** [comment]
+1 - and abort startup if it's not

**Comment by ametaireau** [comment]
In order to do this, you should, in cliquet:

1. Add a "ping" method to the redis backend. It's as simple as `self._client.ping()` which should be exposed as a "ping" method, and called in the `__init__` method. The method should be added here: https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/redis.py#L51
2. Add tests that ensure that an exception is raised in case the ping doesn't work.
3. Do the same for Postgres.

**Comment by Natim** [comment]
The ping method is now externalized from backends here: https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/__init__.py#L245-L271

**Comment by ametaireau** [comment]
Oh! So there is already a ping method to use! Neat. Even simpler then: just call it ;-)
