### ISSUE TITLE
History of changes

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#230]
**issue pending a use case feedback**

Let's add a history of changes in Kinto.

Slightly different from the requests logged into heka, we're only logging here changes made to the database.

Features:
- log each change made to collections : who/when/what (hey, we have notifications for this now ;))
- provide a simple API to retrieve the history  
- maximum history size in days through configuration

**Comment by leplatrem** [comment]
That's a great use case for writing a kinto plugin indeed :)

**Comment by ametaireau** [comment]
Notifications for the win!

**Comment by leplatrem** [comment]
The implementation of history tracking itself is very simple, it is very similar to what was done in kinto-changes (BTW I think this feature should land there).
We could even store a diff between old and new on update etc. 

Among the use-cases we have in mind, there is:

* What was changed in this collection since last time?
* When was this record created?
* What is the history of the collection json schema?


History must thus track and allow filtering/sorting by:

* `resource_name`: every kind of object (bucket, collection, records, ...)
* `prefixed_userid`: userid prefixed by authentication policy
* `action`: create/update/delete
* `uri`: object URI without version prefix

The history is actually a resource whose records are the notifications payloads, that can be filtered, sorted etc. like any other resource but readonly.

But while I was thinking about the implementation, I realized the main challenge was about permissions (especially if we store diffs).

* **Minimalist**: use a setting to specify which principals are allowed to read
* **Per bucket/collection**: readable if read on bucket/collection
* **Filtered per permission**: show only the history entries where the related object is readable. This would probably give the best experience, but would be relatively complex to implement ('cuz of perfs, reminder: permissions can be in redis, history records in postgresql)

Do you have any feedback on the preferred approach? I personnally like the second one as a first step.

**Comment by n1k0** [comment]
> The history is actually a resource whose records are the notifications payloads

Just to be sure, would that mean we could access the resource data itself? Ideally it would be nice to have the previous data (before the action is executed) and the new data (after the action is executed). Maybe this could be rendered conditionally (eg. with `?full=true`) to avoid large entries to bloat the output.

**Comment by Natim** [comment]
About the permission layer I would create the history collection in the same bucket so that we can give permissions to the same groups of the bucket. However we shouldn't automatically detect permissions and just let them be defined in the config as for kinto-changes.

**Comment by leplatrem** [comment]
> Ideally it would be nice to have the previous data and the new data

Yes, this is trivial to implement.

The only concern is about permissions: we have to be sure that those who can read the history would have been allowed to read the affected records.

**Comment by n1k0** [comment]
> The only concern is about permissions: we have to be sure that those who can read the history would have been allowed to read the affected records.

I wonder how silly would be to create a new dedicated permission for that?

**Comment by n1k0** [comment]
Like a *superadmin* permission, explicitly allowing people having that permission set being able to browser everything they weren't originally allowed to. Just having written that scared me so I'm not super sure if it's a good idea.

**Comment by Natim** [comment]
Yes that would be the ``read`` permission on the history of changes.

I can see two plans, either we add the permissions directly on the records (the record permission as well as the collection and bucket permissions to the history record) so that we can see all the history of records we had permissions to see at the time.

Or we can give read permission to the history collection as we usually do for other collections.

For the current use cases we are managing public data so that it shouldn't be a problem.

**Comment by n1k0** [comment]
> Or we can give read permission to the history collection as we usually do for other collections.

Yeah, much simpler, let's do that. We can always document that giving read permission to the history collection is something possibly dangerous, handle with care, etc. 

We should probably ensure that no user can write to that collection as well (writes should be always be performed by the system).

**Comment by Natim** [comment]
> writes should be always be performed by the system

Yes exactly

**Comment by Natim** [comment]
We have started a blueprint about that here: https://github.com/Kinto/kinto/wiki/Kinto-History

**Comment by leplatrem** [comment]
Merged in #694 !
