### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by peteringram0** [Kinto/kinto#347]
I can see kinto.js does not work on IE10 and IE11. What is the browser support on this please?

Thanks,

**Comment by leplatrem** [comment]
The Kinto server is an HTTP service, it works with every browser.

The kinto.js client is absolutely not necessary to use Kinto in a JavaScript application. Using Angular or pure XmlHttpRequest would also work perfectly! 

kinto.js is relevant to provide offline/sync, and relies on IndexedDB, promises etc. to do it. Since it provides the polyfills to run on not-so-modern browsers, it should be ok with IE11. If you have a particular problem with kinto.js on the browser you mention, I suggest that you open an issue on the kinto.js repo instead.

I'm closing this, but feel free to re-open if you still have some doubts !
