### ISSUE TITLE
s/lightweight/simple

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#417]
Following up a discussion about the usage of the word "lightweight" with @leplatrem - I am suggesting removing it from the documentation and replacing it with "simple".

The word "lightweight" has too many different meanings - both positive and negative. Is it lightweight in terms of RAM usage ? of complexity of deployment ? of features ? etc..

Simple seems to me like a word that describes best what is intended with the Kinto **API** : trying to KISS.

**Comment by almet** [comment]
Thanks for bringing this up. I like the idea of not trying to do too much, and I believe that's why we used lightweight.

"Kinto is a lightweight JSON storage service with synchronisation and sharing abilities." would then become "Kinto is a simple JSON storage service with synchronisation and sharing abilities.", and I don't see a lot of value in "simple" in this sentence.

Two alternative proposals:

1. Remove lightweight completely. "Kinto is a JSON storage service [...]"
2. Put a little indicator next to "lightweight", with a link explaining what we mean by that.

**Comment by tarekziade** [comment]
I voe for 1. because "little indicators" won't stick when the text is copied around

**Comment by leplatrem** [comment]
what about minimalist ?

**Comment by almet** [comment]
good idea!
