### ISSUE TITLE
Remove synchronous example in notifications tutorial

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#420]
the notification tutorial at https://github.com/Kinto/kinto/blob/master/docs/tutorials/notifications-custom.rst is showing how to send emails synchronously. 

This is typically what we want to do asynchronously :) 

I propose 2 changes:
- do the e-mail example in the second part (async)
- for the sync example, I propose a piece of code that modifies data in the response (maybe on-the-fly translation of some text ? )

**Comment by tarekziade** [comment]
Another thing: maybe we should store tutorial scripts in real Python modules, we can run tests against. This is useful to make sure the tutorials are really working when the project changes.

**Comment by leplatrem** [comment]
> This is typically what we want to do asynchronously :) 

Yes indeed. Although relying on a fast local server that behaves as relay is a very common approach. 
In the tutorial we mention: 

> To run this in production, we would rely on a local email server acting as a relay in order to avoid bottlenecks. Or use the asynchronous approach otherwise.

If you are willing to improve the tutorials please don't hesitate!

>  do the e-mail example in the second part (async)

Yes why not, if it does not make it too long.

> a piece of code that modifies data in the response

Altering records on the fly can be a bit hacky, I have no idea how'd it look.
Otherwise, we could do something else, like pushing messages to crossbar.io for example.

No other feedback apart from this :) \o/ ?

**Comment by tarekziade** [comment]
>  relying on a fast local server that behaves as relay is a very common approach
> To run this in production, we would rely on a local email server acting as a relay in order to avoid bottlenecks.

Not if you want a robust system.  If there's any issue sending e-mails out, you now have to deal with an HTTP service that fails to return responses to its users because the SMTP service is borked.

If it slows down (it happens even on "very fast" local SMTP services), you're slowing down all requests to your HTTP service.

If I take an example of how Kinto could be deployed at Mozilla : it would use Amazon SES, and I would want to send emails to SES asynchronously.

> If you are willing to improve the tutorials please don't hesitate!

I would not dare changing it until you really feel it's useful !

> Altering records on the fly can be a bit hacky, I have no idea how'd it look.

Me neither, but in my mind the only benefit of synchronous notifications is if it impacts what is written in the DB or what gets back to the user. 

If the triggered notification has zero impact on the request/response flow, what would we ever want it to be synchronously executed ?  just to slow down the user for no reason ?

**Comment by leplatrem** [comment]
> If there's any issue sending e-mails out, you now have to deal with an HTTP service that fails to return responses 

No because [the exceptions raised by listeners are catched](https://github.com/mozilla-services/cliquet/blob/2.15.0/cliquet/resource/__init__.py#L657-L661).

> If the triggered notification has zero impact on the request/response flow, what would we ever want it to be synchronously executed ? just to slow down the user for no reason ?

The default listener that deposits messages in the redis queue is synchronuous. 

A listener that sends messages to a crossbar server would be synchronuous too IMO.

For example, the [listener that sends to Pusher is synchronuous](https://github.com/leplatrem/cliquet-pusher/blob/0.2.0/cliquet_pusher/listener.py#L13-L31) in the current implementation (*I don't say it's the best way to do it though*).

In brief:
* if we can alter the response in a simple and clean manner, let's do that! That's indeed the best illustration.
* otherwise let's find another example! (*Some ideas: populate a «history» collection to track changes, or implement a listener for an alternative third-party to pusher.*)

**Comment by tarekziade** [comment]
> No because the exceptions raised by listeners are catched.

But if the service times out, you still get unacceptable response times.

> The default listener that deposits messages in the redis queue is synchronuous. 

Yes that's something we've discussed when we added it. In that case we're making the assumption that the redis service is dedicated to Kinto usage and we can push to its queue and for example trigger an exception if it's not operating fast enough. We're under control for this queue hopefully.

Ideally, we should have workers **inside Kinto** to deal with this. Example: https://github.com/AcrDijon/henet/blob/master/henet/workers.py

That would be an enhancement and handles your not-really-async not-really-sync examples
