### ISSUE TITLE
let's add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#425]
as pointed by Pascal https://twitter.com/pascalchevrel/status/695533836113936384

Maybe we can have it there and somehow pull it in Sphinx ?

**Comment by almet** [comment]
That's a good idea.

The goals of both documents are not exactly the same, because `CONTRIBUTING.md` will actually be included at the beginning of each pull request. It could then make sense to have `CONTRIBUTING.md` contain some basic instructions that are useful *in the context of a pull request* with for instance a link to our contribute page.

**Comment by tarekziade** [comment]
yeah a brief text with a link to the doc sounds perfect
