### ISSUE TITLE
collection_timestamp on an empty collection get updated at each request with postgresql backend.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#433]
**Reproduce:**

```
  http GET https://kinto-server.scalingo.io/v1/buckets/default/collections/certificates/records --auth token:my-secret
  Etag: "1455109382839"

  http GET https://kinto-server.scalingo.io/v1/buckets/default/collections/certificates/records --auth token:my-secret
  Etag: "1455109385100"
```

**Comment by almet** [comment]
The problem seems to come from [this line](https://github.com/mozilla-services/cliquet/blob/master/cliquet/storage/postgresql/schema.sql#L156) in the psql backend, which takes the greatest value between records timestamp and the current datetime.

We should take the last_modified value of the collection?

**Comment by almet** [comment]
Actually, we would need to set the timestamp during the creation of the collection.
