### ISSUE TITLE
Serve Kinto from a docker container via HTTPS

### ISSUE THREAD

**Issue by doplumi** [Kinto/kinto#527]
Posting here because this might be a bug but feel free to close if it isn't.

http://stackoverflow.com/questions/36332972/how-do-i-serve-kinto-via-https-from-a-docker-container/36334290#36334290

**Comment by leplatrem** [comment]
Currently the Docker container uses `pserve` which does not support https.

Should we use `uwsgi` instead?

**Comment by Natim** [comment]
I would rather go for a docker link with nginx so that nginx handles the SSL offload.

**Comment by domtallo** [comment]
So, I got away but setting up a reverse proxy that handles SSL, which was simpler than I thought. I have Kinto on 8888 and the proxy targeting 8888, listening on 8889 and replying with httpS. And it works: Kinto request on 8889 are not blocked from Chrome anymore.

Now, the problem with this approach is that insecure Kinto at 8888 is still accessible from everybody.

Are you by any chance aware of any waitress/pserve options I could use to make Kinto from the docker container (8888) only reply to the proxy (8889) and no one else? 
@Alexis suggested, over at SO, to use `kinto.http_host` and `kinto.http_port` options to solve this issue but have no idea how!

**Comment by Natim** [comment]
What you can do is to use a socket file so that only process having access to this file can read and write to it. That is the setup we have with uwsgi: http://kinto.readthedocs.org/en/latest/configuration/production.html#running-with-uwsgi

**Comment by leplatrem** [comment]
@domtallo do you have a conclusion to share ? Maybe to put in the FAQ ?
Thanks for your feedback !

**Comment by domtallo** [comment]
@leplatrem: Actually no, I didn't quite understand @Natim advice. 

I am still playing with Kinto so all I need for now is it being accessible from HTTPS, but it would be nice and cleaner to have the server be *only* accessible via HTTPS, especially for production.

If anybody has an easier way to set this up please share.

**Comment by Natim** [comment]
If you use something like that: http://kinto.readthedocs.io/en/stable/configuration/production.html#running-with-uwsgi

For instance it looks like that:

```
[uwsgi]
wsgi-file = app.wsgi
enable-threads = true
socket = /home/ubuntu/.run/uwsgi/kinto.sock
chmod-socket = 666
processes =  3
master = true
module = kinto
harakiri = 120
uid = ubuntu
gid = ubuntu
virtualenv = /home/ubuntu/venvs/kinto
lazy = true
lazy-apps = true
single-interpreter = true
buffer-size = 65535
post-buffering = 65535
```

Then you can run uwsgi and have nginx serve the service in HTTPS with a config like that:

```
server {
    listen 443 ssl;

    server_name kinto.yourdomain.com;

    ssl_certificate /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key /etc/nginx/ssl/certificate.key;

    location /attachments {
        root /home/ubuntu;
    }

    location /v1 {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_intercept_errors on;
        uwsgi_pass unix:///home/ubuntu/.run/uwsgi/kinto.sock;
        uwsgi_read_timeout 120;
        uwsgi_send_timeout 120;
        include uwsgi_params;
    }

    location / {
        return 301 https://$host/v1$request_uri;
    }
}
```

If you need an intermediate certificate chain, you can use this solution: https://scottlinux.com/2013/09/02/how-to-configure-ssl-certificate-chain-for-nginx/

**Comment by Natim** [comment]
You can use this generator to make sure to have a perfect nginx SSL configuration: https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by almet** [comment]
@domtallo: What I understand from your previous messages is that you have a setup which is currently working: you have a reverse proxy doing the SSL offload properly, the only remaining problem you have is that the kinto server itself thinks it's running on the 8888 whereas you would like it to be on the 443 (HTTPS) protocol.

The message from @natim is proposing a different solution to what you currently have in place (Currently you have a docker container listening to a specific port, and outside the docker a reverse proxy doing the SSL offloading, from what I understand). The setup you have seems to be working, except from the host and port parts.

In order to do this, you can configure the kinto server (with the kinto.ini file) telling it the correct host and port.

Here is the link to the documentation: http://kinto.readthedocs.io/en/latest/configuration/settings.html#scheme-host-and-port, in your case, it means that your `kinto.ini` file should have the following configuration:

```ini
kinto.http_scheme = https
kinto.http_host = kinto.yourserver.tld
```

Hope that helps

**Comment by almet** [comment]
Also, if you're interested in how I setup haproxy to do SSL offloading, have a look at https://github.com/almet/infra/blob/master/haproxy/haproxy.cfg
