### ISSUE TITLE
[cliquet] Add PATCH on collections

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto#609]
original : https://github.com/mozilla-services/cliquet/issues/274

The title says it all. I guess WHY NOT? and there's a use case it seems

**Comment by gabisurita** [comment]
How do you fell about this improvement at the moment? My main concern is pagination and batch limits from settings. Should we support these? In case we do, what happens if we exceed the limit?

@leplatrem @Natim

**Comment by Natim** [comment]
I don't think it is a great improvment since we can already do the exact same thing with batch requests.
It will add a new endpoints with potentially new bugs while in terms of API it won't be more efficient or faster.

I don't think we should worry about pagination rules but maybe using the batch limits could be important.
If we exceed the limit we could have the same error that we have with the batch endpoint.

**Comment by leplatrem** [comment]
Ok, let's close it then?

**Comment by Natim** [comment]
That's probably why we are discussing it. Do we want to implement it or close it?

**Comment by gabisurita** [comment]
> I don't think we should worry about pagination rules but maybe using the batch limits could be important. If we exceed the limit we could have the same error that we have with the batch endpoint.
I don't think we can use the same protocol for batch because batch requests are ordered, but I don't think we can assume the same for collection PATCH.

IDK. If you think it makes sense I can implement it. While working on the rust client I was thinking that this could be useful to simplify the synchronization protocol but it also brings several related issues (e.g. limits, history entries, logging, performance). Thinking through it maybe it brings more problems than solutions.

Also, I don't think this is an easy pick.

**Comment by leplatrem** [comment]
Closing until we have a concrete use-case.
