### ISSUE TITLE
Generate Swagger API declaration

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#631]
We talked about it at Djangocong, it would be really good to add automatic functional tests and documentation.

Refs https://github.com/mozilla-services/cliquet/issues/257

**Comment by almet** [comment]
Related to https://wiki.mozilla.org/Outreachy#Add_support_for_OpenAPI_to_Kinto

**Comment by Natim** [comment]
Yes it is :dancer:

**Comment by leplatrem** [comment]
https://larlet.fr/david/blog/2016/specifications-apis/

**Comment by leplatrem** [comment]
Some notes/ideas:

Instead of generating the Swagger from the source code, which seems very hard based on the services definitions only. We could edit it by hand and then make sure it remains up-to-date with a plugin like pyramid-swagger

Editing it by hand can be tedious in our case since we have many properties that are repeated accross the API.

We can imagine to edit by hand several small pieces of yaml/json and have a way to assemble them towards a final big spec file. Also, depending on settings or what plugins are installed the list of endpoints may change... I wonder how that should come into play.
