### ISSUE TITLE
There's still a problem with browser caching

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#635]
It seems adding the `Vary` header to responses didn't entirely solve the issue we had with cached authenticated responses in the browser.

[This fiddle](https://jsfiddle.net/n1k0/5axpdbbj/3/) reproduces the issue against the kinto dev server, where you can see by running the script at least twice that the second time the responses are cached and served to distinct authenticated requests.

The issue is reproducible in both Firefox and Chrome.

First user response for `GET /buckets`:

![](http://i.imgur.com/SfgWnWX.png)

Second user response  for `GET /buckets`:

![](http://i.imgur.com/c7YPpLP.png)

Notice the two distinctly used Authorization headers sent, and the the two equivalent responses obtained. In the second capture, the second user received a cached response containing data from the first user. That's rather annoying.

**Comment by leplatrem** [comment]
The browser automatically adds `If-None-Match` and `If-Modified-Since` based on the first responses. The server returns 304 and the client reuses the former response.

I could fix the fiddle with this hack:
```js
  return fetch(base + path, {
  	headers: {
      Authorization: "Basic " + btoa(`${user}:${pass}`),
      "If-None-Match": "",
      "If-Modified-Since": "",
    }
  })
```

I read the specs:
- **13.4 Response Cacheability** 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.4
- **14.9.1 What is Cacheable**
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8

I felt dumb, I don't understand 100% of it.

As @almet recommended, I digged in Gecko source code. And found [the piece of code that is responsible for the behaviour that we see](https://dxr.mozilla.org/mozilla-central/rev/46fe2115d46a5bb40523b8466341d8f9a26e1bdf/netwerk/protocol/http/nsHttpChannel.cpp#3608-3658)

I could understand that the client tries to «validate» its cache with those `If-Last-Modified` and `If-None-Match`. In our case, the server returns 304 (ie. no new object created meanwhile) , so the client thinks it can re-use its cache!


## `Cache-Control: no-store` should do it.

Then, when my eyes had burnt, I found a very useful page, by Google, which makes it very clear:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

> “no-cache” indicates that the returned response cannot be used to satisfy a subsequent request to the same URL without first checking with the server if the response has changed. As a result, if a proper validation token (ETag) is present, no-cache will incur a roundtrip to validate the cached response, but can eliminate the download if the resource has not changed.

> By contrast, “no-store” is much simpler, as it simply disallows the browser and all intermediate caches to store any version of the returned response - e.g. one containing private personal or banking data. Everytime the user requests this asset, a request is sent to the server and a full response is downloaded each and every time.

I came back to the spec. This is still... opaque.

> 14.9.2 What May be Stored by Caches
> 
> no-store
>    The purpose of the no-store directive is to prevent the inadvertent release or retention of sensitive information (for example, **on backup tapes**). [...]

**Comment by Natim** [comment]
What about ``Cache-Control: private``

**Comment by n1k0** [comment]
Interesting read & discussion https://bugzilla.mozilla.org/show_bug.cgi?id=269303

In this thread I feel we can replace the term "Cookie" with "Authorization". Excerpts:

> Afterall, if the entity depends on the value of the Cookie header, then you really have two (or more) different entities.

> This is another reason why entity-tags are better than last-modified time stamps
for validating cache entries.  If you use last-modified as the cache validator,
then you are saying essentially that the URL is enough to uniquely identify the
content.

This is something that I've been asking for a while, so here it is again: is there anything preventing us to forge authentication-aware ETag values? eg `"userid-1234567890"` instead of just `"1234567890"`.

**Comment by Natim** [comment]
Using authentication aware ETag would break the API.
