### ISSUE TITLE
Include last_modified alongside data when serving records (and generating signatures)

### ISSUE THREAD

**Issue by mozmark** [Kinto/kinto#687]
Collection signing is great bu we need to embed some monotonically increasing value in the signed data so we know collections aren't being reverted to some old state (see https://bugzilla.mozilla.org/show_bug.cgi?id=1280877).

Instead of serving `{data:[...]} `as we do now, could we instead serve something like
`{data:[...], last_modified:1466419311856}`?

**Comment by almet** [comment]
I believe this is related to https://github.com/Kinto/kinto/issues/256

**Comment by mozmark** [comment]
Related, yes. In this case, the collection last_modified and the record last_modified communicate different things.

Let's say we have a collection. Imagine a record is added, then removed.  If a client syncs at the start, then again between the addition and removal and then, finally, syncs again after removal. Currently, the response body containing records will be the same in the first and last case. Also, the last_modified state based on (signed) data the client can see looks the same. but I need to be able to distinguish between the two (and determine the order in which all three responses belong) from signed data.

**Comment by almet** [comment]
I understand better, thanks!

One other way I can think of that seems to solve this would be to always include the deleted items in the sync and in the collection. In the Kinto server, there is actually a difference between something that exists and something that existed and was removed, thanks to the use of tombstones.

Would this solve your problem? 

It doesn't really matters, but note that this issue should probably be handled in [the kinto signer](https://github.com/Kinto/kinto-signer)

**Comment by Natim** [comment]
Isn't it already the ETag header's role?

**Comment by mozmark** [comment]
@Natim the ETag does have this data - but it needs to be part of the signed response if we wish to prevent replay of signed content.

@almet I wasn't sure. Should I close it and file it there?

**Comment by Natim** [comment]
> It needs to be part of the signed response if we wish to prevent replay of signed content.

Oh that is an interesting edge case.
I am a bit reluctant at changing the Kinto protocol for that.

- Could we add the ETag value in the signature body before generating it without changing the response body?
- Should we always return the tombstone records as @almet was suggesting?

**Comment by almet** [comment]
Thinking a bit more about it, it brings another important security feature to the mix.
An attacker could prevent an update to be applied in the clients.

Downloading all the deleted records does not seem to fix this specific issue, though.

Should we have a way to have a kind of heartbeat feature between the clients and the server. e.g. a way to check that the downloaded files are not more than a 2d old? How would we accomplish this?

I'm not sure this is what you have in mind @mozmark , if it isn't I should probably open another issue on the signer for this.

Let's continue the discussion here for now I think.

**Comment by Natim** [comment]
> e.g. a way to check that the downloaded files are not more than a 2d old?

This is not a solution we have case when the collection is not updated in two days and when users will start Firefox once a month.

**Comment by almet** [comment]
You need to be sure that your list is up to date, otherwise an attacker can just block the requests by serving an old version.

We could have something that updates the collection on a daily basis for instance, and when clients start their browser, it will first download the list I believe, so we are covered. The thing it should check for is that the list it gets from the server is one that is actually not more than X days old (this check is done on the retrieved list and not on the cached list on the client).

However, this is possible only if SSL is broken, so it might not be an issue for Firefox clients which pin their SSL certs ? (but still remains an issue for all other use cases which do not pin the SSL).

**Comment by mozmark** [comment]
I'm slightly less worried about availability issues than I am integrity issues (since a determined attacker can arrange for other kinds of DoS) but it is a real problem. Especially since an attacker can 'fake' a successful sync (and we use 'last success' as a way to determine certain behaviours in my use-case).

Some kind of signed heartbeat is what we'd need were we to decide to resolve that, @almet - this would need to be separate from actual collection updates because of what @natim describes. Maybe @jvehent has thoughts on this?

**Comment by leplatrem** [comment]
I may not grasp everything that is at stake here, but as Natim suggested: why don't we add the Etag to the body before signing?

On the server, it may require a minor change in kinto-signer, and in the client, we have it at hand ([see http client](https://github.com/Kinto/kinto-http.js#listing-records)] and [in sync incoming hooks](http://kintojs.readthedocs.io/en/latest/extending/#hooks))

Since you mention the idea of a *signed heartbeat*, I guess that the above proposition is not enough :)

**Comment by leplatrem** [comment]
This was implemented in the kinto-signer plugin v.0.7.0.

Closing :)
