### ISSUE TITLE
Accounts API

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#795]
The current approach with Basic Auth has very strong limitations. Mainly:
- It is hard to refresh the token (aka password) (every object permissions have to be modified before doing it)
- It is hard (if not impossible) to avoid users loosing their permissions [when rotating the hmac secret](https://github.com/Kinto/kinto/issues/691)

I propose that we make a simplistic `kinto.plugins.accounts` plugin that will: 
- Add a new CRUD resource (`/accounts`) where only the `create` permission is given
- The schema will be `id` (email regex?), `password` (PBKDF2, bcrypt or whatever) and additional metadata
- The object id would be forced to what is provided in basic auth header as user value
- Provide an `account` authentication policy using basic auth that will lookup in storage backend

When defining permissions on object it could just be `account:robert@patulacci.fr`.

To control who is allowed to create users, we would rely on the setting `kinto.account_create_principals` (like for buckets). When reaching the list of accounts, they would only their own object. Since they created the object, they would be allowed to modify and delete it.

We could deprecated the usage of the current basic auth.

I believe it would make authentication a bit more intuitive in Kinto, and would still be very easy to get started or deploy.

What do you think ?

**Comment by Natim** [comment]
Yes, let's do that :)

**Comment by n1k0** [comment]
This is brilliant and will greatly improves the developer experience :)

**Comment by glasserc** [comment]
I like it too!

**Comment by almet** [comment]
Nice, @enguerran just mentioned on IRC this would be useful to him :)

**Comment by ptgamr** [comment]
+1

**Comment by Natim** [comment]
Maybe keeping Kinto user management outside of Kinto is still a good idea. I wish we could colaborate around #933

**Comment by almet** [comment]
So, do we have a plan for shipping this in the next releases?

**Comment by leplatrem** [comment]
The PR is still WIP, if anyone wants to give a hand, more than welcome! It's mainly a matter of documentation now :)

**Comment by kulshekhar** [comment]
I've been exploring kinto and it looks very promising - except for the authentication story. I came across this issue, took a look at portier & kinto-portier and think that this looks like a great solution.

I'd like to do what I can to help get this in. Since I'm not familiar with the codebase, if someone can tell me what needs to be done, I can give it a shot!

**Comment by Natim** [comment]
I guess starting with a tutorial explaining the issue with Authentication and how people can plug the backend they'd like would be great.
One thing would be to add an OpenID-Connect compliant authentication backend. (kinto-fxa could be a great start for that).
And of course the accounts plugin, that would allow to create users with their profile, eventually plug multiple authentication mecanisms to them, or create anonymous accounts that they can activate so that you can create things and give permissions to people not having an account on your kinto just yet.

Few days ago I've started [a Blueprint about it](https://github.com/Kinto/kinto/wiki/Account-invitations-by-SMS-and-email-notifications) It would be nice to review it, improve it and implement a proof of concept.

@kulshekhar if you feel like driving this we will help you for sure. Do not hesitate to join our slack channel

- [ ] Tutorial about authentication with Kinto
- [ ] kinto-openidconnect
- [ ] kinto-accounts

**Comment by leplatrem** [comment]
Before broadening the scope of this too much and adding new things on the pile, let's go back to the *accounts API* feature.

The code of this PR was ready. I was thinking that we could rewrite the whole project documentation to rely on it instead of basic auth. And that last part never happened because it represents a lot of documentation effort. 

From here, we can imagine several strategies (*add yours!*):
* Merge it as an hidden/experimental feature (ie. just code, no docs)
* Merge it and document it as an extra feature (ie. without rewriting every docs)
* Merge it once the whole documentation is ready (ie. requires lots of efforts)
* Move it to a separate repo for less friction and keep the core repo as small as possible
* Drop this PR (which has hackish parts) and rely on a more solid solution like Portier by default (see #994) 


-----------

> I guess starting with a tutorial explaining the issue with Authentication and how people can plug the backend they'd like would be great.

This requires a good knowledge of Kinto. I don't know if that's an easy start at all. We never wrote it, and the current docs were never super clear about auth (ex. #976).   

> One thing would be to add an OpenID-Connect compliant authentication backend. (kinto-fxa could be a great start for that).

This is another topic. See #939 and #508 

> eventually plug multiple authentication mecanisms to them

This would deserve a dedicated issue.

>  create anonymous accounts that they can activate so that you can create things and give permissions to people not having an account on your kinto just yet.

This would deserve a dedicated issue.

**Comment by kulshekhar** [comment]
@leplatrem I'm new to kinto but if I had a little bit on how to start exploring & using the accounts API (just a paragraph or two), I could play with it and start documenting it.

**Comment by Natim** [comment]
That would be awesome.
