### ISSUE TITLE
Create buckets/groups/collections using file/configuration

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto#84]
It would be nice to have a command that takes a file as an input and creates buckets/collections/groups, and permissions...

```
kinto initialize --server https://kinto.dev.mozaws.net/v1/ conf/payments.json
```

**Comment by Natim** [comment]
We did something like that for OneCRL: https://github.com/mozilla-services/xml2kinto

It could be a start to generalize.

**Comment by Natim** [comment]
I would rather create a script in a distinct repository and with a distinct release workflow because I do not want people to have to install Kinto and all its dependencies just to import/export from kinto.

I have created https://github.com/Kinto/kinto-setup (We may want to rename it into kinto-dump at some point)

I'd like to have something that POST on the batch endpoint to setup the kinto service and that can also take a list of resources to generate the export.json file that can then be passed as a BATCH.

I will keep you posted.

**Comment by Natim** [comment]
This is even more useful with the new kinto-admin.

We need to let people create collection with schema, ui-schema and displayFields quite easily. I will start to think about it.

**Comment by Natim** [comment]
I have started a Blueprint here: https://github.com/Kinto/kinto/wiki/Handling-permission-on-a-Kinto-Server

**Comment by leplatrem** [comment]
https://github.com/Kinto/kinto-wizard/ was started :) closing here!
